apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: my-app-container
          image: my-app:stg
          env:
            - name: ENVIRONMENT
              value: "staging"